spring:
  profiles:
    active: development
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
---
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://postgresql:5432/sampleDataBase
server:
  port: 8080
