spring:
  profiles:
    active: development
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
---
spring:
  profiles: development
  jpa:
    show_sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://postgresql:5432/sampleDataBase
    username: username
    password: password
server:
  port: 8080
